[project]
name = "sudolver"
version = "0.1.0"
description = "A sudoku solver."
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.5",
    ]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pytest-mock>=3.14.0",
    "ruff>=0.11.9",
]
